# This is a basic workflow to help you get started with Actions

name: PDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  GeneratePdf:
    runs-on: ubuntu-latest
    container: node:12.18.2
    steps:
      - uses: actions/checkout@v2
      
      - name: Install packages
        run: |
          apt update
          apt install fonts-roboto libfontconfig -y
      
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      # Runs a set of commands using the runners shell
      - name: Run npm preparation script
        run: npm ci --cache .npm --prefer-offline
      
      - name: Generate menus
        run: node ./scripts/generate-menu.js
      
      - name: Generate PDFs
        run: node ./scripts/generate-pdf.js
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: pdf
          path: |
            pdf
      
  DeployPdf:
    runs-on: ubuntu-latest
    needs: [GeneratePdf]
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: pdf
  
      - name: AWS CLI
        uses: ItsKarma/aws-cli@v1.70.0    
        with:
          args: s3 cp . s3://${{ secrets.BUCKET_NAME }}/manuals --include "*.pdf" --recursive --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}  
